/******************************************************************************/
/****              Generated by IBExpert 24/07/2020 20:36:32               ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TEST_TABLE (
    ID     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    MEMO   BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    XTS    DOM_TIMESTAMP_NULL = TIMESTAMP,
    XDATE  DOM_DATE_NULL = DATE ,
    XBLOB  DOM_BLOB = BLOB SUB_TYPE 0 SEGMENT SIZE 80 ,
    XTEXT DOM_CHAINE_100_NULL = VARCHAR(100) ,
    XTIME  DOM_TIME = TIME DEFAULT CURRENT_TIME NOT NULL
);




/******************************************************************************/
/****                       Autoincrement generators                       ****/
/******************************************************************************/


ALTER TABLE TEST_TABLE ALTER ID RESTART WITH 2574;




/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TEST_TABLE ADD CONSTRAINT PK_TEST_TABLE PRIMARY KEY (ID);


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON TEST_TABLE TO TEST2;
